const Data = [
	{
		id: "1",
		image: require("./assets/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "2",
		image: require("./assets/profile2.png"),
		name: "Profile 2",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "3",
		image: require("./assets/profile3.png"),
		name: "Profile 3",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "4",
		image: require("./assets/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "5",
		image: require("./assets/profile2.png"),
		name: "Profile 2",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "6",
		image: require("./assets/profile3.png"),
		name: "Profile 3",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "7",
		image: require("./assets/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "8",
		image: require("./assets/profile2.png"),
		name: "Profile 2",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "9",
		image: require("./assets/profile3.png"),
		name: "Profile 3",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "10",
		image: require("./assets/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "11",
		image: require("./assets/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "12",
		image: require("./assets/profile2.png"),
		name: "Profile 2",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "13",
		image: require("./assets/profile3.png"),
		name: "Profile 3",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "14",
		image: require("./assets/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "15",
		image: require("./assets/profile2.png"),
		name: "Profile 2",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "16",
		image: require("./assets/profile3.png"),
		name: "Profile 3",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "17",
		image: require("./assets/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "18",
		image: require("./assets/profile2.png"),
		name: "Profile 2",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "19",
		image: require("./assets/profile3.png"),
		name: "Profile 3",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
];

export { Data };
